version: '3.8'

services:
  php:
    build: .
    container_name: php_server
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src/config:/var/www/private/config
      - ./src/controllers:/var/www/private/controllers
      - ./src/lib:/var/www/private/lib
      - ./src/router:/var/www/private/router
      - ./src/views:/var/www/private/views
      - ./src/utility:/var/www/private/utility
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learnphp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
